import enum


class HandlerType(str, enum.Enum):
    MAIN_INITIATED = 'main_initiated'
    MAIN_JOINED = 'main_joined'
    MAIN_LEFT = 'main_left'
    ROOM_JOINED = 'room_joined'
    ROOM_LEFT = 'room_left'
    ROOM_NOT_STARTED = 'room_not_started'
    ROOM_STARTED = 'room_started'
    ROOM_JOB_INITIATED = 'room_job_initiated'
    ROOM_STATUS_CHANGED = 'room_status_changed'
    MEMBER_STATUS_CHANGED = 'member_status_changed'
    JOB_CHANGED = 'job_changed'
    CREATE_ROOM = 'create_room'
    JOIN_ROOM = 'join_room'
    CHANGE_NAME = 'change_name'
    TOGGLE_STATUS = 'toggle_status'
    COMMON_SEND = 'common_send'
    JOB_LIST = 'job_list'
    VOTE_CHANGED = 'vote_changed'
    TARGET_CHANGED = 'target_changed'
    JOB_TARGET_DONE = 'job_target_done'
    CHOOSE_CHANGED = 'choose_changed'
    CANNOT_CHOOSE = 'cannot_choose'
    ROOM_MEMBER_CHANGED = 'room_member_changed'
    ROOM_INITIATED = 'room_initiated'
    MAIN_CHANGED = 'main_changed'
    GAME_DONE = 'game_done'
